# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - MLogWebApp

on:
  push:
    branches:
      - Azure-1.0.0.1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Build React App
        run: |
          cd frontend  # Navigate to the frontend directory
          npm install   # Install React dependencies
          npm run build # Build the React application

      - name: Zip artifact for deployment
        run: |
          cd frontend/build # Navigate to the build output directory
          zip -r ../../release.zip .  # Zip the *contents* of the build directory

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B3E067979ECB431CAE8EDFB81651C920 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0F6FB07E6C9940BC956BDD5305BB674B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D3401DF5C43E48639D0145A328B62C71 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MLogWebApp'
          slot-name: 'Production'
          package: .
          
